### ISSUE TITLE
Verifying cookie contents are valid

### ISSUE THREAD

**Issue by DevanB** [justincy/nextjs-auth#1]
Thanks for this great example of how to handle redirects based on cookies.

I was considering using this setup, but wanted to verify I understand one point correctly. My cookies will store a session token that I can use to determine if the session is still valid. I’m guessing I could make the request to my backend [here](https://github.com/justincy/nextjs-client-auth-architectures/blob/master/ssr-ts/src/hocs/withAuth.tsx#L20).

I figured it’d be worth asking since you seem to understand this more than me :)

**Comment by justincy** [comment]
You could do that, as long as you updated `withConditionalRedirect` to support `serverCondition` being an async function. 

But I would ask what you're trying to accomplish with that. The session only needs to be validated when retrieving data and therefore validation typically only happens in an API. That would mean that if a user's session expired, the app would render the page and request data, then the API would detect the expired session and return an error response (typically a 401), and then the app would respond accordingly.

Validating the session server-side in the next app is just an optimization by detecting the expired session earlier at the expense of a slower server response (because you have to wait for the session validation request before rendering finishes on the server and it can send the HTML to the client). In other words, you're optimizing for the expired-session scenario at the expense of all other requests with valid sessions.

Does that make sense?

At least that's how I see it, but I don't claim to have all the answers. I created this repo to discover the intricacies of this auth behavior, to share what I learned, and to get feedback, so feedback is welcome.

**Comment by DevanB** [comment]
Thinking through this more, I believe you are correct!

I'm unsure of using a hook in a function that isn't a React function component nor a custom React hook function (`useIsAuthenticated`). Additionally if you use `getInitialProps` in `_app`, Next can't perform automatic static optimizations meaning every page will be server rendered. You can see more about that [here](https://nextjs.org/docs/advanced-features/custom-app). I'm still working through the best way to handle this as some pages may not need to be server-rendered, like a login page.

I like that the frontend knows if the user is authenticated, but not at the expense of every page being server-side rendered.

**Comment by justincy** [comment]
@DevanB You are correct about the pitfalls of `getInitialProps`. That's why this repo also has an example of a [static architecture](https://github.com/justincy/nextjs-client-auth-architectures/tree/master/static) for accomplishing the same thing.
